a = "GTTGGTTGGTGTCTCCTCCACTCCTGGTTCTTATAGCCCAATATCTGCTTCTCAGTTCAAGAGTGCTGGAGTCCATTGTTTCCATATTCTCATTTGAAGCAATTTGAACTCCTCGAGTGGATAGTTGCCCTCTTGGGACT"
b = "GTTGGTTGGTGTTTCCTCCACTCCTGGTTCTTATAGCCCAATATCTGCTTCTCAGTTCAAGAGTGCTGGAGTCCATTGTTTCCATATTCTCATTTGAAGCAATTTGAACTCCTCGAGTGGATAGTTGTCCTCTTGGGACT"

for i in range(len(a)):
    if a[i] != b[i]:
        print(i)